name: 'Unified Minecraft Mod Publisher'
description: 'Publishes a Minecraft mod to CurseForge, Modrinth, and a Release'
inputs:
  jar-signing-store:
    description: 'Optional. Base64 encoded jar signing store'
    required: false
    default: ''
  jar-signing-alias:
    description: 'Optional. Alias for jar signing'
    required: false
    default: ''
  jar-signing-store-pass:
    description: 'Optional. Key password for jar signing'
    required: false
    default: ''
  jar-signing-key-pass:
    description: 'Optional. Store password for key signing'
    required: false
    default: ''

  mod-file:
    description: 'Mod file to upload.'
  version-name:
    description: 'Name for this version of the mod'
  minecraft-version:
    description: 'The version of Minecraft this is compatible with'
  mod-loader:
    description: 'Modloader(s) this mod is compatible with'
  mod-environment:
    description: 'The environment this mod works in. Defaults to both Client and Server.'
    required: false
    default: 'Client,Server'
  changelog:
    description: 'Changelog'
    required: false
    default: 'Autogenerated'
  min-java-version:
    description: 'Minimum required Java version for this mod'
    required: false
    default: '17'
  max-java-version:
    description: 'Latest compatible Java version for this mod'
    required: false
    default: '22'
  rename-version:
    description: 'Whether to append "-{version}" to the end of the mod filename before submitting'
    required: false
    default: false
  include-md5-changelog:
    description: 'Whether to include an MD5 hash in the changelog'
    required: false
    default: true

  curse-project-id:
    description: 'The Project ID on CurseForge'
    required: false
    default: ${undefined}
  curse-token:
    description: 'The CurseForge auth token to use'
    required: false
    default: ${undefined}

  modrinth-project-id:
    description: 'The Project ID on Modrinth'
    required: false
    default: ${undefined}
  modrinth-token:
    description: 'The Modrinth auth token to use'
    required: false
    default: ${undefined}
  
  dependencies:
    description: 'Mod Dependencies'
    required: false
    default: ''
  github-token:
    description: 'GitHub Token'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: "3.10"
    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: ${{ inputs.min-java-version }}
    - id: process
      name: "Process action data"
      run: python ${{ github.action_path }}
      shell: bash
      env:
        MOD_FILE: "${{ inputs.mod-file }}"
        CHANGELOG: "${{ inputs.changelog }}"
        INCLUDE_MD5_CHANGELOG: "${{ inputs.include-md5-changelog }}"
        MC_VERSION: "${{ inputs.minecraft-version }}"
        MOD_LOADER: "${{ inputs.mod-loader }}"
        MOD_ENVIRONMENT: "${{ inputs.mod-environment }}"
        MIN_JAVA_VERSION: "${{ inputs.min-java-version }}"
        MAX_JAVA_VERSION: "${{ inputs.max-java-version }}"
        JAR_SIGNING_STORE: "${{ inputs.jar-signing-store }}"
        JAR_SIGNING_ALIAS: "${{ inputs.jar-signing-alias }}"
        JAR_SIGNING_STORE_PASS: "${{ inputs.jar-signing-store-pass }}"
        JAR_SIGNING_KEY_PASS: "${{ inputs.jar-signing-key-pass }}"
    - name: "Upload"
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        modrinth-id: ${{ inputs.modrinth-project-id }}
        modrinth-token: ${{ inputs.modrinth-token }}

        curseforge-id: ${{ inputs.curse-project-id }}
        curseforge-token: ${{ inputs.curse-token }}

        github-token: ${{ inputs.github-token }}

        changelog-file: CHANGELOG

        files: ${{ steps.process.outputs.mod_file }}

        loaders: ${{ inputs.mod-loader }}
        game-versions: ${{ inputs.minecraft-version }}
        dependencies: ${{ inputs.dependencies }}
        java: ${{ steps.process.outputs.java_version }}

        version: ${{ inputs.version-name }}
