name: 'Unified Minecraft Mod Publisher'
description: 'Publishes a Minecraft mod to CurseForge, Modrinth, and a Release'
inputs:
  jar-signing-store:
    description: 'Optional. Base64 encoded jar signing store'
    required: false
    default: ''
  jar-signing-alias:
    description: 'Optional. Alias for jar signing'
    required: false
    default: ''
  jar-signing-store-pass:
    description: 'Optional. Key password for jar signing'
    required: false
    default: ''
  jar-signing-key-pass:
    description: 'Optional. Store password for key signing'
    required: false
    default: ''

  mod-file:
    description: 'Mod file to upload.'
  version-name:
    description: 'Name for this version of the mod'
  minecraft-version:
    description: 'The version of Minecraft this is compatible with'
  mod-loader:
    description: 'Modloader(s) this mod is compatible with'
  mod-environment:
    description: 'The environment this mod works in. Defaults to both Client and Server.'
    required: false
    default: 'Client,Server'
  changelog:
    description: 'Changelog'
    required: false
    default: 'Autogenerated'
  min-java-version:
    description: 'Minimum required Java version for this mod'
    required: false
    default: '17'
  max-java-version:
    description: 'Latest compatible Java version for this mod'
    required: false
    default: '22'
  rename-version:
    description: 'Whether to append "-{version}" to the end of the mod filename before submitting'
    required: false
    default: false
  include-md5-changelog:
    description: 'Whether to include an MD5 hash in the changelog'
    required: false
    default: true

  curse-project-id:
    description: 'The Project ID on CurseForge'
    required: false
    default: ''
  curse-token:
    description: 'The CurseForge auth token to use'
    required: false
    default: ''
  curse-relations:
    description: 'Mod relations on CurseForge'
    required: false
    default: ''

  modrinth-project-id:
    description: 'The Project ID on Modrinth'
    required: false
    default: ''
  modrinth-token:
    description: 'The Modrinth auth token to use'
    required: false
    default: ''
  modrinth-dependencies:
    description: 'Dependencies on Modrinth'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.10
    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: ${{ inputs.min-java-version }}
    - id: process
      name: "Process action data"
      run: python ${{ github.action_path }}
      shell: bash
      env:
        MOD_FILE: "${{ inputs.mod-file }}"
        CHANGELOG: "${{ inputs.changelog }}"
        INCLUDE_MD5_CHANGELOG: "${{ inputs.include-md5-changelog }}"
        MC_VERSION: "${{ inputs.minecraft-version }}"
        MOD_LOADER: "${{ inputs.mod-loader }}"
        MOD_ENVIRONMENT: "${{ inputs.mod-environment }}"
        MIN_JAVA_VERSION: "${{ inputs.min-java-version }}"
        MAX_JAVA_VERSION: "${{ inputs.max-java-version }}"
        JAR_SIGNING_STORE: "${{ inputs.jar-signing-store }}"
        JAR_SIGNING_ALIAS: "${{ inputs.jar-signing-alias }}"
        JAR_SIGNING_STORE_PASS: "${{ inputs.jar-signing-store-pass }}"
        JAR_SIGNING_KEY_PASS: "${{ inputs.jar-signing-key-pass }}"
    - name: "Upload to CurseForge"
      if: ${{ inputs.curse-token }} != ''
      uses: itsmeow/curseforge-upload@v3
      with:
        file_path: "${{ steps.process.outputs.mod_file }}"
        game_endpoint: "minecraft"
        relations: "${{ inputs.curse-relations }}"
        game_versions: ${{ steps.process.outputs.curse_version }}
        project_id: "${{ inputs.curse-project-id }}"
        token: "${{ inputs.curse-token }}"
        changelog_type: text
        changelog: ${{ steps.process.outputs.changelog }}
    - name: Upload to Modrinth
      uses: cloudnode-pro/modrinth-publish@1.0.0
      with:
        token: ${{ inputs.modrinth-token }}
        project: ${{ inputs.modrinth-project-id }}
        file: "${{ steps.process.outputs.mod_file }}"
        changelog: ${{ steps.process.outputs.changelog }}
        loaders: "${{ inputs.mod-loader }}"
        dependencies: "${{ inputs.modrinth-dependencies }}"
        api-domain: "api.modrinth.com"